*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCDS_ALV_DISPLAYU01.
                    "Z_CDS_ALV_FULL_SCREEN
INCLUDE LZCDS_ALV_DISPLAYU02.
                    "Z_CDS_ALV_SPLIT_SCREEN