*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ Z_CDS_ALV_EXTENSIONS_DIALOG

    IMPORTING
       REFERENCE(I_CDS_VIEW) TYPE !DDSTRUCOBJNAME
    RAISING
       !ZCX_CDS_ALV_MESSAGE.