PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCDS_ALV_EXTHDR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCDS_ALV_EXTHDR-EXTENSION_NAME .
    FIELD ZCDS_ALV_EXTHDR-ALTERNATIVE_SELECTION .
    FIELD ZCDS_ALV_EXTHDR-ALTERNATIVE_DISPLAY .
    FIELD ZCDS_ALV_EXTHDR-IMPLEMENTING_CLASS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.
    FIELD ZCDS_ALV_EXTHDRT-EXTENSION_TEXT .
    FIELD ZCDS_ALV_EXTHDRT-SELECTION_TEXT .
    FIELD ZCDS_ALV_EXTHDRT-DISPLAY_TEXT .
    MODULE SET_TXT_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCDS_ALV_EXTHDR-EXTENSION_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.