PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMCDSALVPROGRAM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMCDSALVPROGRAM-CDS_VIEW .
    FIELD ZMCDSALVPROGRAM-PROGNAME .
    FIELD ZMCDSALVPROGRAM-DYNPRO .
    FIELD ZMCDSALVPROGRAM-AUTHOR .
    FIELD ZMCDSALVPROGRAM-GENERATED_AT .
    FIELD ZMCDSALVPROGRAM-NO_GENERATION .
    FIELD ZMCDSALVPROGRAM-ADD_FUNC_DISPLAY_MODE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMCDSALVPROGRAM-CDS_VIEW .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.