*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCDS_ALV_TABLESU01.
                    "TABLEFRAME_ZCDS_ALV_TABLES
INCLUDE LZCDS_ALV_TABLESU02.
                    "TABLEPROC_ZCDS_ALV_TABLES