  METHOD get_fallback_static.
    r_class = SWITCH #( i_interface
      WHEN 'ZIF_CDS_ALV_FACTORY'            THEN 'ZCL_CDS_ALV_FACTORY'
      WHEN 'ZIF_CDS_ALV_DDIC_ACCESS'        THEN 'ZCL_CDS_ALV_DDIC_ACCESS'
      WHEN 'ZIF_CDS_ALV_PERSISTENCE'        THEN 'ZCL_CDS_ALV_PERSISTENCE'
      WHEN 'ZIF_CDS_ALV_MEMORY'             THEN 'ZCL_CDS_ALV_MEMORY'
      WHEN 'ZIF_CDS_ALV_REPORT_GENERATOR'   THEN 'ZCL_CDS_ALV_REPORT_GENERATOR'
      WHEN 'ZIF_CDS_ALV_REPORT_LAUNCHER'    THEN 'ZCL_CDS_ALV_REPORT_LAUNCHER'
      WHEN 'ZIF_CDS_ALV_NAVIGATION'         THEN 'ZCL_CDS_ALV_NAVIGATION'
      WHEN 'ZIF_CDS_ALV_GRID_BUILDER'       THEN 'ZCL_CDS_ALV_GRID_BUILDER'
      WHEN 'ZIF_CDS_ALV_SELECTION'          THEN 'ZCL_CDS_ALV_SELECTION'
      WHEN 'ZIF_CDS_ALV_SELECTION_SCREEN'   THEN 'ZCL_CDS_ALV_SELECTION_SCREEN'
      WHEN 'ZIF_CDS_ALV_CONDITION_PROVIDER' THEN 'ZCL_CDS_ALV_SELECTION_SCREEN'
      WHEN 'ZIF_CDS_ALV_VALUE_HELP'         THEN 'ZCL_CDS_ALV_VALUE_HELP'
      WHEN 'ZIF_CDS_ALV_REPORT_CONTROLLER'  THEN 'ZCL_CDS_ALV_REPORT_CONTROLLER'
      WHEN 'ZIF_CDS_ALV_REPORT_STRATEGY'    THEN 'ZCL_CDS_ALV_REPORT_STRATEGY'
      WHEN 'ZIF_CDS_ALV_ACTION_HANDLER'     THEN 'ZCL_CDS_ALV_ACTION_HANDLER'
      WHEN 'ZIF_CDS_ALV_BOPF_HANDLER'       THEN 'ZCL_CDS_ALV_BOPF_HANDLER'
      WHEN 'ZIF_CDS_ALV_AUTHORITY_CHECK'    THEN 'ZCL_CDS_ALV_AUTHORITY_CHECK'
      WHEN 'ZIF_CDS_ALV_TABLE_CONTAINER'    THEN 'ZCL_CDS_ALV_TABLE_CONTAINER'
      WHEN 'ZIF_CDS_ALV_EXTENSION_PROVIDER' THEN 'ZCL_CDS_ALV_EXTENSION_PROVIDER' ).
  ENDMETHOD.