PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_SO_KEY.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD  SO_KEY-LOW.
  FIELD  SO_KEY-HIGH.
  MODULE %_SO_KEY.
ENDCHAIN.

FIELD !P_MAXREC MODULE %_P_MAXREC .

FIELD !P_NO_MAX MODULE %_P_NO_MAX .


CHAIN.
  FIELD  SO_KEY-LOW.
  FIELD  SO_KEY-HIGH.
  FIELD P_MAXREC .
  FIELD P_NO_MAX .
    MODULE %_BLOCK_1001001.
ENDCHAIN.

FIELD !P_SPLIT MODULE %_P_SPLIT .

CHAIN.
  FIELD  SO_KEY-LOW.
  FIELD  SO_KEY-HIGH.
  FIELD P_MAXREC .
  FIELD P_NO_MAX .
  FIELD P_SPLIT .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD SO_KEY-LOW MODULE %_SO_KEY-LOW_VAL .
  FIELD SO_KEY-HIGH MODULE %_SO_KEY-HIGH_VAL .